version: "1"

# Configuration de la base de données PostgreSQL
databases:
  - name: gestion_employer
    databaseName: employer_zfnr
    user: root
    plan: free
    region: oregon
    postgresMajorVersion: "16"
    ipAllowList:
      - source: 0.0.0.0/0  # Sécuriser en remplaçant par une IP spécifique
        description: "Accès depuis toutes les IPs"

# Configuration du service web
services:
  - type: web
    name: mon-app-django
    env: python
    plan: free
    region: oregon

    # Commandes de déploiement
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&  # Appliquer les migrations automatiquement
      gunicorn gestion_employe.wsgi:application  # Démarrer l'application avec Gunicorn

    # Variables d'environnement pour la base de données et le super utilisateur
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestion_employer
          property: connectionString

      - key: DJANGO_SUPERUSER_USERNAME
        value: ${DJANGO_SUPERUSER_USERNAME:-admin}  # Valeur par défaut si non définie
      - key: DJANGO_SUPERUSER_PASSWORD
        value: ${DJANGO_SUPERUSER_PASSWORD:-admin123}  # Valeur par défaut si non définie
      - key: DJANGO_SUPERUSER_EMAIL
        value: ${DJANGO_SUPERUSER_EMAIL:-admin@example.com}  # Valeur par défaut si non définie

    autoDeploy: true
