# render.yaml - Configuration Render complète et optimisée
version: "1"

databases:
  - name: gestion_employer
    databaseName: employer_zfnr
    user: root
    plan: free
    region: oregon
    postgresMajorVersion: "16"

    # ⚠️ Pour plus de sécurité, remplace 0.0.0.0/0 par ton IP uniquement
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

services:
  - type: web
    name: mon-app-django
    env: python
    plan: free
    region: oregon

    buildCommand: pip install -r requirements.txt

    startCommand: |
      python manage.py migrate &&
      gunicorn gestion_employe.wsgi:application

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestion_employer
          property: connectionString

      - key: DJANGO_SUPERUSER_USERNAME
        value: admin

      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123

      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com

    autoDeploy: true
